### ISSUE TITLE
Make a more precise model

### ISSUE THREAD

**Issue by oramsey** [nmsu-cs/project-vote4us#14]
The model works with some pictures of Waldo, but we likely need to make a model that runs through more epochs, maybe around 500, and remove some of the dark and unclear images from the dataset.

**Comment by LTiede4** [comment]
I think we should also take more pictures of waldo on phone screens, people dressed up as waldo, etc... because that is likely what would be seen when we use it.

**Comment by LTiede4** [comment]
Waldo V2 has been uploaded, it has had a minor improvement from 67% certainty to 75% certainty.

What we learned is that more epochs create a better model, but we are experiencing diminishing returns.

Now, we must gather more images that add variety to the training dataset.

**Comment by oramsey** [comment]
the model works pretty well now.
