### ISSUE TITLE
Create either a new ML file or new function to Train Waldo 

### ISSUE THREAD

**Issue by LTiede4** [nmsu-cs/project-vote4us#4]
We have working code in 'MLTest' that runs a machine learning model on live video and an image. However, the model that is being run is a pretrained opencv ML model.

The way that these are run is by calling cv2. **trainedModel(** _video/image_ **)**

We need to make either a function in MLTest.py or a new file like the way opencv does, that executes a trained model for Waldo.

It is likely that this issue will have several sub-issues. I can imagine that the "training" and "executing" actions are separate tasks, and that the "training" task will require some work.

**Comment by oramsey** [comment]
made the MLtest file and used the trainWaldo() function
