### ISSUE TITLE
Create an executable file that will set up the virtual environment and download the necessary libraries for the user

### ISSUE THREAD

**Issue by LTiede4** [nmsu-cs/project-vote4us#5]
Imma be frank. I followed this tutorial on YouTube to make the machine learning model:
https://youtu.be/V62M9d8QkYM

Then I realized that I needed to make a virtual environment to follow the tutorial. So I then followed this tutorial to do that:
https://youtu.be/GZbeL5AcTgw

Sounds fine right? NO. I tried replicating this process so that I could make it really simple for everyone else to do, but now I'm having issues replicating what I already did.

I suppose the question that I will need to answer is whether I even need this virtual environment, or if I can just get the library files necessary and just push those. I'm not sure if that is bad practice, or if that is against the law.

**Comment by romn6** [comment]
I was viewing some videos on uploading data into out ML model that also involves the use of Py. We can definitely incorporate
ideas from this into our model. Check this out: 
https://www.youtube.com/watch?v=eivDTOlA0TE

**Comment by LTiede4** [comment]
This .exe experience can eventually be used to make an .exe for the entire project.

**Comment by LTiede4** [comment]
we have a working executable that sets up the machine learning libraries. This can and will be used to set up the jfx stuff as well
