### ISSUE TITLE
Figure out how to make the python and java files interact

### ISSUE THREAD

**Issue by LTiede4** [nmsu-cs/project-vote4us#6]
At some point (hopefully in the near future), we're going to have to figure out how to make the python an java files communicate.

Or we could just switch everything to python, but I think it would be a good idea to figure this out, because it seems like a valuable thing to know.

**Comment by romn6** [comment]
We could look into something called "Jython" which is java & python, to which we can make interact both Java & Python, and view what packages/libraries are found within it. That's if we dont move everything to python.

**Comment by LTiede4** [comment]
I've found somewhat of a solution to allow the gui to implement the frames being output by the machine learning model, but I think that this is not a good long-term solution because this is a fixed image size.

What would work better, is to output the xmin, ymin, xmax, ymax, for drawing the box to then be used by the gui file... maybe. We might come up with a better solution at some point.

**Comment by LTiede4** [comment]
this is already an issue. deleting the duplicate
