### ISSUE TITLE
Make Tests for ML file

### ISSUE THREAD

**Issue by LTiede4** [nmsu-cs/project-vote4us#7]
There needs to be a file that tests the functions of the 'MLTest.py' file (which probably should've been named 'MLTest.py')

Right now there are no functions to test, but that can be made quickly.

This file will be continually added upon as time goes on, I'd imagine.

**Comment by oramsey** [comment]
we made image, video, and live video tests

**Comment by oramsey** [comment]
![Screenshot (51)](https://github.com/nmsu-cs/project-vote4us/assets/123403359/401287f4-bd0c-463c-825c-bc65fea61c0f)

**Comment by oramsey** [comment]
![umlpic](https://github.com/nmsu-cs/project-vote4us/assets/123403359/e66b0ca8-f6fd-4ac3-8dc9-7d99edcc7cc1)
